name: cs234_final_project
channels:
  - conda-forge
dependencies:
  - python=3.10.16
  - numpy
  - pandas
  - scipy
  - matplotlib
  - gym
  - pytorch
  - stable-baselines3
  - clawpack
  - pip
  - scikit-learn
  - tensorboard
  - pip:
      - stable-baselines3
